### ISSUE TITLE
npx を使えるようにする

### ISSUE THREAD

**Issue by ykws** [ykws/zenn-content#1]
別の環境で npx を使おうとしたらエラーが出るので、これを解消したい。

## やったこと

https://github.com/ykws/hello-node

```
% brew --version
Homebrew 3.3.9
Homebrew/homebrew-core (git revision 3350a85a8ac; last commit 2022-01-01)

% brew install n
% n --version  
v8.0.1

% sudo n latest
Password:
  installing : node-v17.3.0
       mkdir : /usr/local/n/versions/node/17.3.0
       fetch : https://nodejs.org/dist/v17.3.0/node-v17.3.0-darwin-arm64.tar.xz
   installed : v17.3.0 (with npm 8.3.0)

% node -v
v17.3.0

% npx zenn new:article --slug *** --title "***" --type idea --emoji ✨
npm ERR! Cannot convert undefined or null to object

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ykws/.npm/_logs/2022-01-01T13_35_58_759Z-debug-0.log
```

<details>
<summary>error log</summary>
<pre>
<code>
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'zenn',
0 verbose cli   'new:article',
0 verbose cli   '--slug',
0 verbose cli   '***',
0 verbose cli   '--title',
0 verbose cli   '***',
0 verbose cli   '--type',
0 verbose cli   'idea',
0 verbose cli   '--emoji',
0 verbose cli   '✨'
0 verbose cli ]
1 info using npm@8.3.0
2 info using node@v17.3.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/ykws/Workspace/GitHub/ykws/zenn-content/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/Users/ykws/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 3ms
19 timing npm:load:configload Completed in 3ms
20 timing npm:load:setTitle Completed in 9ms
21 timing config:load:flatten Completed in 1ms
22 timing npm:load:display Completed in 2ms
23 verbose logfile /Users/ykws/.npm/_logs/2022-01-01T13_35_58_759Z-debug-0.log
24 timing npm:load:logFile Completed in 2ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 16ms
28 http fetch GET 200 https://registry.npmjs.org/zenn 150ms (cache revalidated)
29 timing command:exec Completed in 156ms
30 verbose stack TypeError: Cannot convert undefined or null to object
30 verbose stack     at Function.keys (<anonymous>)
30 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:213:22)
30 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
30 verbose stack     at async /usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:106:12
30 verbose stack     at async Promise.all (index 0)
30 verbose stack     at async exec (/usr/local/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:94:17)
30 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:66:5)
31 verbose cwd /Users/ykws/Workspace/GitHub/ykws/zenn-content
32 verbose Darwin 20.6.0
33 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "zenn" "new:article" "--slug" "***" "--title" "***" "--type" "idea" "--emoji" "✨"
34 verbose node v17.3.0
35 verbose npm  v8.3.0
36 error Cannot convert undefined or null to object
37 verbose exit 1
38 timing npm Completed in 241ms
39 verbose code 1
40 error A complete log of this run can be found in:
40 error     /Users/ykws/.npm/_logs/2022-01-01T13_35_58_759Z-debug-0.log
</code>
</pre>
</details>

**Comment by ykws** [comment]
https://github.com/ykws/hello-node

で Node は動くので Node の問題ではなさそう
